### ISSUE TITLE
sensor.yaml bug

### ISSUE THREAD

**Issue by chk2902** [lowprize/homeassistant-solax-api#1]
`        friendly_name: "Solax Inverter AC power total"  
        value_template: '{{ states.sensor.solax_api.attributes["result"]["acpower"] }}'
        unit_of_measurement: "kW"
        device_class: energy`

should be

`        friendly_name: "Solax Inverter AC power total"  
        value_template: '{{ states.sensor.solax_api.attributes["result"]["acpower"] }}'
        unit_of_measurement: "W"
        device_class: power`

**Comment by lowprize** [comment]
Thx you, updated
